server:
  servlet:
    context-path: /api

spring:
  profiles:
    active: devp
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  mail:
    host: smtp.yandex.ru
    port: 465
    username: test
    password: test
    properties:
      "mail.transport.protocol": smtp
      "mail.smtp.auth": true
      "mail.smtp.starttls.enable": true
      "mail.debug": false
      "mail.smtp.ssl.enable": true

#spring.freemarker.expose-request-attributes=true

jwt:
  secret: justew
  expiration: 604800
  header: Authorization

path:
  mainPage: /
  upload: /C:/Project/manager/image
  css: /css/**
  js: js/**
  images: /images/**
  swagger: /swagger-ui.html
  webjars: /webjars/**
  swaggerResources: /swagger-resources/**
  apiDocs: /v2/api-docs
  static: =classpath:/static/

URI:
  image: /img/**
  static: /static/**

confirmationExpiredTime: 86400

authentication:
  maxFailedLoginAttempts: 100
  blockPeriodInMinutes: 10
