spring:
  datasource:
    url: jdbc:postgresql://localhost/postgres
    username: sa
    password: sa
    driverClassName: org.postgresql.Driver
  data:
    redis:
      host: localhost
      port: 6379
      password: passWd

  mail:
    host: smtp.yandex.ru
    port: 465
    username: test
    password: test
    properties:
      "mail.transport.protocol": smtp
      "mail.smtp.auth": true
      "mail.smtp.starttls.enable": true
      "mail.debug": false
      "mail.smtp.ssl.enable": true

  jpa:
    show-sql: false
    hibernate.ddl-auto: validate
    properties:
      hibernate:
        default_schema: test

  flyway:
    schemas: test

logging:
  level:
    root: INFO
    org.springframework.security: INFO
    org.springframework.web: INFO
    org.hibernate: INFO
    com.manager: INFO
    com.manager.finance.metric: DEBUG
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG

metric:
  executionTime: true

URI:
  application: http://localhost:8080