spring:
  datasource:
    url: jdbc:postgresql://manager_database:5432/postgres
    username: sa
    password: sa
    driverClassName: org.postgresql.Driver

  mail:
    host: smtp.yandex.ru
    port: 465
    username: test
    password: test
    properties:
      "mail.transport.protocol": smtp
      "mail.smtp.auth": true
      "mail.smtp.starttls.enable": true
      "mail.debug": false
      "mail.smtp.ssl.enable": true

  jpa:
    show-sql: false
    hibernate.ddl-auto: validate
    properties:
      hibernate:
        default_schema: public

  flyway:
    schemas: public

logging:
  level:
    root: INFO
    org.springframework.security: INFO
    org.springframework.web: INFO
    org.hibernate: INFO
    com.manager: TRACE
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG

URI:
  application: http://localhost:8080